#cloud-config

package_update: true

packages:
 - python3-pip
 - groff
 - libicu-dev
 - emacs25

runcmd:
  - [ sh, -c, "sudo apt install --assume-yes docker.io" ]
  - [ sh, -c, "sudo docker run --detach --name vm.nginx --publish 80:80 nginx" ]
